### ISSUE TITLE
Token for backup file names

### ISSUE THREAD

**Issue by amilenkov** [backdrop-contrib/backup_migrate#19] opened 2016-06-05 09:09 UTC
https://backdropcms.org/project/backup_migrate - there is written:
"Enable token.module to allow token replacement in backup file names."

Now token.module is in core but I can not see tokens for backup file names.

Am I mistaken or this function will be added later?

![edit_settings_profile](https://cloud.githubusercontent.com/assets/14857883/15804570/4c729370-2b16-11e6-91dd-5ee1c818f0a1.png)

**Comment by quackers8me** [comment] 2016-08-26 23:49
I have confirmed on my system that this works. If you have set your 'site name' in: admin/config/system/site-information
It will automatically pull that token [site:name] into backup migrate as the backup file name.

**Comment by amilenkov** [comment] 2016-08-28 09:17
But in my system this is still not working. 
Core is Backdrop 1.4.4. 
Here is my site information:
![site_information_ _ _ _-_2016-08-28_11 59 02](https://cloud.githubusercontent.com/assets/14857883/18032711/479c6644-6d17-11e6-98ef-dc36ee85bdb1.png)

This is Edit Settings Profile as default:
admin/config/system/backup_migrate/settings/profile/edit/default
You can see that there is no list of tokens for selection.

![edit_settings_profile_ _ _ _-_2016-08-28_12 04 15](https://cloud.githubusercontent.com/assets/14857883/18032719/95c57df6-6d17-11e6-92e1-68dc9fb3ca08.png)

If you do a manual backup:
![01_backup_ _ _ _-_2016-08-28_12 07 53](https://cloud.githubusercontent.com/assets/14857883/18032733/13167fbc-6d18-11e6-8f77-b73bfc6147e5.png)

the following message is received:
![01_backup_ _ _ _-_2016-08-28_12 10 29](https://cloud.githubusercontent.com/assets/14857883/18032737/71f7de18-6d18-11e6-8d18-3bcffe675f45.png)
There is no Backup file name - only date stamp.

If I change settings and fill in a site name token manually:
![edit_settings_profile_ _ _ _-_2016-08-28_12 13 18](https://cloud.githubusercontent.com/assets/14857883/18032750/d44a9268-6d18-11e6-879a-74e7f39d2fe5.png)

and make a backup again - the following message is received:
![01_backup_ _ _ _-_2016-08-28_12 15 24](https://cloud.githubusercontent.com/assets/14857883/18032761/21fe143a-6d19-11e6-9450-e6aa918828be.png)

There is no real site name again - only the token [site:name] is converted to sitename.

**Comment by quackers8me** [comment] 2016-08-29 17:04
Hi @amilenkov after further review, the Token function was not being called properly since it was moved to core. I have now fixed that and created a new release.

BUT, the issue you initially reported is not related to tokens but to the use of non-ascii characters in your site name.

``` php
/**
 * Clean up a filename to remove unsafe characters.
 */
function _backup_migrate_clean_filename($filename) {
  $filename = preg_replace("/[^a-zA-Z0-9\.\-_]/", "", $filename);
  return $filename;
}
```

To support your language it would require some further development and possibly add dependencies with other modules which I'm unable to do at this time.
You may find another replacement pattern that will work for you or you may have to manually use an ascii filename.

![backup_migrate_token](https://cloud.githubusercontent.com/assets/10571471/18059844/290ca9ca-6dd8-11e6-9b94-522ba53ab5ed.png)

Cheers,
Jason

**Closed as completed by quackers8me** 2016-08-29 17:04 UTC

**Comment by klonos** [comment] 2016-09-01 00:21
@amilenkov, @quackers8me transliteration is now in core (since 1.3.0). You can enable the "Transliterate prior to creating URL aliases" option in `/admin/config/search/path/patterns/settings` for now and that should take care of non-ASCII characters 😉

**Comment by quackers8me** [comment] 2016-09-01 02:21
Thanks Gregory.
Keep in mind that even if you do use Transliteration, you will need to use
the [site:url] tokens.
